#使用默认配置
server:
  port: 10002
spring:
  application:
    name: tensquare-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.70.19:3306/eke?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 120.78.70.19
    port: 6379
  jpa:
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 120.78.70.19

snowflake:
  systemCode: 1
  workCode: 1