# 雪花id
snowflake:
  systemCode: 2
  workCode: 1

#使用默认配置
server:
  port: 10002
spring:
  application:
    name: tensquare-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.70.19:3306/eke?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 120.78.70.19
    port: 6379
  jpa:
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 120.78.70.19

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
  instance:
    prefer-ip-address: true
  # 此处为自行配置
  server:
    hostname: localhost
    port: 19999
feign:
  hystrix:
    enabled: true